# workflow for deploying the documentation

name: Deploy Code Documentation on Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy_document:
    name: 'Deploy Code Documentation'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run jsdocs script'
        run: npm run docs

      - name: 'Publish the document on github pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
